### ISSUE TITLE
Led color "Invalid Param"

### ISSUE THREAD

**Issue by antonioepuglisiRHA** [DHowett/FrameworkWindowsUtils#9]
Hi, 
running on a AMD Framework 13, I try to run the EC tool to change the color of the power led but every time I do I receive this error:
EC result 3 (INVALID_PARAM)

same thing happens with left and right, but with battery I manage to change both the side leds. 

I have to note that I can turn off the Power led and turn it back on, but I cannot change the color of the led.

.\ectool.exe led power amber 

What can I do to fix this? I am running the latest ECtool released here with the latest Bios 3.05

**Comment by DHowett** [comment]
Hey, sorry about that! On the Laptop 13 AMD, Laptop 13 Core Ultra 1, and Laptop 16 AMD the power key only supports `white`. In addition, on these models, the side LEDs are not addressable separately (you need to use `battery` like you figured out.)

This is unfortunately a limitation of the embedded controller firmware itself.

I know that they removed the color LEDs from the fingerprint power LED to align with the Framework Chromebook which only supported a single color.
